### PR TITLE
separate line numbers from code

### PR DESCRIPTION
**Pull request by uiii**
Hi, I've implemented an improvement where the line numbers are separated form code in source code view. It really makes my life easier because I often copy the code from here. I'm sure everyone will appreciate this. There has nothing changed visually.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi @uiii , thanks for contribution. Seems like great idea to me.

Could I ask you to send same PR to [BootstrapTheme](https://github.com/ApiGen/ThemeBootstrap)?

**Comment by uiii** [comment]
Great. I'm not using BootstrapTheme, but I'll look at it.

**Comment by uiii** [comment]
Done.

**Comment by uiii** [comment]
Is there anything what blocks the PR to be merged?

**Comment by TomasVotruba** [comment]
Not really, thank you!

**Pull request merged**
